import { motion, AnimatePresence } from 'framer-motion';
import { X, Sparkles, Copy, Check, AlignLeft, ListChecks } from 'lucide-react';
import { useState } from 'react';

const SummaryModal = ({ isOpen, onClose, summary }) => {
    const [copied, setCopied] = useState(false);

    if (!isOpen || !summary) return null;

    const handleCopy = () => {
        const text = `${summary.short}\n\n${summary.bullets?.join('\n- ')}`;
        navigator.clipboard.writeText(text);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const container = {
        hidden: { opacity: 0 },
        show: {
            opacity: 1,
            transition: {
                staggerChildren: 0.1
            }
        }
    };

    const item = {
        hidden: { opacity: 0, x: -20 },
        show: { opacity: 1, x: 0 }
    };

    return (
        <AnimatePresence>
            {isOpen && (
                <>
                    {/* Backdrop */}
                    <motion.div
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        exit={{ opacity: 0 }}
                        onClick={onClose}
                        className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 flex items-center justify-center p-4"
                    >
                        {/* Modal */}
                        <motion.div
                            initial={{ opacity: 0, scale: 0.95, y: 30 }}
                            animate={{ opacity: 1, scale: 1, y: 0 }}
                            exit={{ opacity: 0, scale: 0.95, y: 30 }}
                            onClick={(e) => e.stopPropagation()}
                            className="bg-white dark:bg-[#1e1e1e] w-full max-w-2xl rounded-2xl shadow-2xl overflow-hidden border border-gray-100 dark:border-gray-700 max-h-[85vh] flex flex-col"
                        >
                            {/* Header */}
                            <div className="p-6 border-b border-gray-100 dark:border-gray-700 flex justify-between items-center bg-gray-50/80 dark:bg-[#252525]">
                                <div className="flex items-center gap-3">
                                    <div className="p-2.5 bg-gradient-to-br from-purple-100 to-indigo-100 dark:from-purple-900/30 dark:to-indigo-900/30 rounded-xl text-purple-600 dark:text-purple-400 shadow-sm">
                                        <Sparkles size={22} />
                                    </div>
                                    <div>
                                        <h2 className="text-xl font-bold text-gray-800 dark:text-gray-100">
                                            AI Smart Summary
                                        </h2>
                                        <p className="text-xs text-gray-500 dark:text-gray-400 font-medium">
                                            Generated by Gemini
                                        </p>
                                    </div>
                                </div>
                                <div className="flex items-center gap-2">
                                    <button
                                        onClick={handleCopy}
                                        className="p-2 hover:bg-white dark:hover:bg-gray-700 rounded-lg text-gray-500 hover:text-gray-700 dark:hover:text-gray-300 transition-all shadow-sm border border-transparent hover:border-gray-200 dark:hover:border-gray-600"
                                        title="Copy to clipboard"
                                    >
                                        {copied ? <Check size={20} className="text-green-500" /> : <Copy size={20} />}
                                    </button>
                                    <button
                                        onClick={onClose}
                                        className="p-2 hover:bg-red-50 dark:hover:bg-red-900/20 hover:text-red-500 rounded-lg text-gray-400 transition-colors"
                                    >
                                        <X size={20} />
                                    </button>
                                </div>
                            </div>

                            {/* Content */}
                            <div className="p-6 overflow-y-auto custom-scrollbar">
                                {/* Short Summary */}
                                <div className="mb-8">
                                    <div className="flex items-center gap-2 mb-3 text-sm font-semibold text-gray-400 uppercase tracking-wider">
                                        <AlignLeft size={16} />
                                        <h3>Overview</h3>
                                    </div>
                                    <div className="bg-gradient-to-r from-purple-50 to-indigo-50 dark:from-purple-900/10 dark:to-indigo-900/10 p-5 rounded-2xl border border-purple-100 dark:border-purple-800/30">
                                        <p className="text-gray-800 dark:text-gray-200 leading-relaxed text-lg font-medium">
                                            {summary.short}
                                        </p>
                                    </div>
                                </div>

                                {/* Bullets */}
                                {summary.bullets && summary.bullets.length > 0 && (
                                    <div className="mb-2">
                                        <div className="flex items-center gap-2 mb-4 text-sm font-semibold text-gray-400 uppercase tracking-wider">
                                            <ListChecks size={16} />
                                            <h3>Key Highlights</h3>
                                        </div>
                                        <motion.ul
                                            variants={container}
                                            initial="hidden"
                                            animate="show"
                                            className="grid gap-3"
                                        >
                                            {summary.bullets.map((bullet, idx) => (
                                                <motion.li
                                                    key={idx}
                                                    variants={item}
                                                    className="flex gap-4 p-3 hover:bg-gray-50 dark:hover:bg-gray-800/50 rounded-xl transition-colors group"
                                                >
                                                    <span className="flex-shrink-0 w-8 h-8 flex items-center justify-center rounded-lg bg-blue-100/50 dark:bg-blue-900/20 text-blue-600 dark:text-blue-400 text-sm font-bold group-hover:scale-110 transition-transform">
                                                        {idx + 1}
                                                    </span>
                                                    <p className="text-gray-600 dark:text-gray-300 leading-relaxed pt-1">
                                                        {bullet}
                                                    </p>
                                                </motion.li>
                                            ))}
                                        </motion.ul>
                                    </div>
                                )}
                            </div>
                        </motion.div>
                    </motion.div>
                </>
            )}
        </AnimatePresence>
    );
};

export default SummaryModal;
